routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\AgenController;
use App\Http\Controllers\ReportPenjualanController;
use App\Http\Controllers\InfoCoronaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::match(["get","post"],"/register", function(){
    return redirect('login');
})->name("register");

Route::group(['middleware' => ['auth']], function(){
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user','App\Http\Controllers\UserController');
Route::resource('supplier', SupplierController::class)->except(['show']);
Route::resource('pegawai', PegawaiController::class)->except('show');
Route::resource('kategori', KategoriController::class)->except('show');
Route::resource('produk', ProdukController::class)->except('show');
Route::resource('transaksi_masuk', TransaksiMasukController::class)->only(['index', 'create', 'store', 'destroy']);
Route::get('agen', [AgenController::class, 'index'])->name('agen');
Route::get('report_penjualan', [ReportPenjualanController::class, 'index'])->name('report_penjualan');
Route::get('cetak_pdf', [ReportPenjualanController::class, 'cetak_pdf'])->name('cetak_pdf');
Route::get('cetak_excel', [ReportPenjualanController::class, 'cetak_excel'])->name('cetak_excel');
Route::get('corona', [InfoCoronaController::class, 'index'])->name('corona');


});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'Supplier';
    protected $primaryKey = 'kd_supplier';
    protected $fillable = [
        'nama_supplier',
        'alamat_supplier'
    ];
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;
use Validator;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $supplier = Supplier::paginate(5);
        $filterKeyword = $request->get('keyword');
        if ($filterKeyword)
        {
            //dijalankan apabila ada pencarian
            $supplier = Supplier::where('nama_supplier','LIKE',"%$filterKeyword%")->paginate(5);
        }
        return view('supplier.index', compact('supplier'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validasi = Validator::make($data,[
            'nama_supplier'=> 'required|max:255',
            'alamat_supplier'=> 'required|max:255'
        ]);

        if($validasi->fails())
        {
            return redirect()->route('supplier.create')->withInput()->withErrors($validasi);
        }

        Supplier::create($data);
        return redirect()->route('supplier.index')->with('status', 'Supplier berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::findOrFail($id);
        return view ('supplier.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::findOrFail($id);
        $data = $request->all();
        
        $validasi = Validator::make($data, [
            'nama_supplier'=> 'required|max:255',
            'alamat_supplier'=> 'required|max:255'
        ]);

        if($validasi->fails())
        {
            return redirect()->route('supplier.edit',[$id])->withErrors($validasi);
        }

        $supplier->update($data);
        return redirect()->route('supplier.index')->with('status', 'Supplier berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::findOrFail($id);
        $supplier->delete();
        return redirect()->route('supplier.index')->with('status', 'Supplier berhasil didelete');
    }
}

resources/views/supplier/create.blade.php
@extends('layouts.template')

@section('title')
    Tambah Data Supplier
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('supplier.store') }}">
          {{ csrf_field() }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="nama_supplier" class="col-sm-2 control-label">Nama Supplier</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="nama_supplier" name="nama_supplier" value="{{ old('nama_supplier') }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="alamat_supplier" class="col-sm-2 control-label">Alamat Supplier</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="alamat_supplier" name="alamat_supplier">{{ old('alamat_supplier') }}</textarea>
                </div>
              </div>                            

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('supplier.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Save</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/supplier/edit.blade.php
@extends('layouts.template')

@section('title')
    Edit Data Supplier
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('supplier.update',[$supplier->kd_supplier]) }}">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="nama_supplier" class="col-sm-2 control-label">Nama Supplier</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="nama_supplier" name="nama_supplier" value="{{ $supplier->nama_supplier }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="alamat_supplier" class="col-sm-2 control-label">Alamat Supplier</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="alamat_supplier" name="alamat_supplier">{{ $supplier->alamat_supplier }}</textarea>
                </div>
              </div>              
            </div>

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('supplier.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Update</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/supplier/index.blade.php
@extends('layouts.template')

@section('title')
    Data Supplier
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                @if(Request::get('keyword'))
                    <a class="btn btn-success" href="{{ route('supplier.index') }}">Back</a>
                @else
                    <a class="btn btn-success" href="{{ route('supplier.create') }}"><span class="glyphicon glyphicon-plus"></span> Create</a>
                @endif                

                <form method="get" action="{{route('supplier.index')}}">
                    <div class="form-group">
                    <label for="keyword" class="col-sm-2 control-label">Search By Name</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="keyword" name="keyword" value="{{ Request::get('keyword') }}">
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
                    </div>
                    </div>
                </form>                            
            </div>
            <div class="panel panel-body">
                @if(Request::get('keyword'))
                    <div class="alert alert-success alert-block">
                        Hasil pencarian supplier dengan keyword : <b>{{ Request::get('keyword') }}</b>
                    </div>
                @endif

                @include('alert.success')

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Nama Supplier</th>
                            <th>Alamat Supplier</th>                            
                            <th width="30%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($supplier as $row)
                            <tr>
                                <td>{{ $loop->iteration + ($supplier->perpage() * ($supplier->currentPage() -1) ) }}</td>
                                <td>{{ $row->nama_supplier }}</td>
                                <td>{{ $row->alamat_supplier }}</td>                                
                                <td>                                    
                                    <form method="post" action="{{ route('supplier.destroy',[$row->kd_supplier]) }}" onsubmit="return confirm('Apakah Anda Yakin Akan Menghapus Data Ini?');">
                                    @csrf
                                    {{ method_field('delete') }}
                                        <a class="btn btn-warning" href="{{ route('supplier.edit', [$row->kd_supplier]) }}">Edit</a>
                                        <button type="submit" class="btn btn-danger">Delete</button>                                    
                                    </form>
                                </td>
                            </tr>                            
                        @endforeach
                    </tbody>
                </table>
                {{ $supplier->appends(Request::all())->links() }}                
            </div>
          </div>
        </div>
    </div>
@endsection

resources/views/supplier/show.blade.php
@extends('layouts.template')

@section('title')
    Detail Data User
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">                             
                <a class="btn btn-success" href="{{ route('user.index') }}">Back</a>                    
            </div>
            <div class="panel panel-body">            
                <table class="table table-bordered">
                    <tr>
                        <td>Username</td>
                        <td>:</td>
                        <td>{{ $user->username }}</td>
                    </tr>
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>:</td>
                        <td>{{ $user->email }}</td>
                    </tr>
                    <tr>
                        <td>Level</td>
                        <td>:</td>
                        <td>{{ $user->level }}</td>
                    </tr>
                </table>
            </div>
          </div>
        </div>
    </div>
@endsection