routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\AgenController;
use App\Http\Controllers\ReportPenjualanController;
use App\Http\Controllers\InfoCoronaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::match(["get","post"],"/register", function(){
    return redirect('login');
})->name("register");

Route::group(['middleware' => ['auth']], function(){
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user','App\Http\Controllers\UserController');
Route::resource('supplier', SupplierController::class)->except(['show']);
Route::resource('pegawai', PegawaiController::class)->except('show');
Route::resource('kategori', KategoriController::class)->except('show');
Route::resource('produk', ProdukController::class)->except('show');
Route::resource('transaksi_masuk', TransaksiMasukController::class)->only(['index', 'create', 'store', 'destroy']);
Route::get('agen', [AgenController::class, 'index'])->name('agen');
Route::get('report_penjualan', [ReportPenjualanController::class, 'index'])->name('report_penjualan');
Route::get('cetak_pdf', [ReportPenjualanController::class, 'cetak_pdf'])->name('cetak_pdf');
Route::get('cetak_excel', [ReportPenjualanController::class, 'cetak_excel'])->name('cetak_excel');
Route::get('corona', [InfoCoronaController::class, 'index'])->name('corona');


});

app/Models/Kategori.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    use HasFactory;

    protected $table = 'kategori';
    protected $primaryKey = 'kd_kategori';
    protected $fillable = [
        'kategori',
        'gambar_kategori'
    ];
}

app/Http/Controllers/Api/KategoriController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Kategori;
use App\Http\Resources\KategoriResource;

class KategoriController extends Controller
{
    public function get_all()
    {
        return KategoriResource::collection(Kategori::all());
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Kategori;
use Validator;
use Storage;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $kategori = Kategori::paginate(5);
        $filterKeyword = $request->get('keyword');
        if($filterKeyword)
        {
            $kategori = Kategori::where('kategori', 'LIKE', "%$filterKeyword%")->paginate(5);
        }

        return view('kategori.index', compact('kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validasi = Validator::make($data, [
            'kategori'=> 'required|max:255',
            'gambar_kategori'=> 'required|image|mimes:jpeg,jpg,png|max:2048'
        ]);

        if($validasi->fails())
        {
            return redirect()->route('kategori.create')->withErrors($validasi)->withInput();
        }

        $gambar_kategori = $request->file('gambar_kategori');
        $extension = $gambar_kategori->getClientOriginalExtension();

        if($request->file('gambar_kategori')->isValid())
        {
            $namaFoto = "kategori/".date('YmdHis').".".$extension;
            $upload_path = 'public/uploads/kategori';
            $request->file('gambar_kategori')->move($upload_path, $namaFoto);
            $data['gambar_kategori'] = $namaFoto;
        }

        Kategori::create($data);
        return redirect()->route('kategori.index')->with('status', 'Kategori berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $kategori = Kategori::findOrFail($id);
        return view('kategori.edit', compact('kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $kategori = Kategori::findOrFail($id);
        $data = $request->all();

        $validasi = Validator::make($data, [
            'kategori'=> 'required|max:255',
            'gambar_kategori'=> 'sometimes|nullable|image|mimes:jpeg,jpg,png|max:2048'
        ]);

        if($validasi->fails())
        {
            return redirect()->route('kategori.edit', [$id])->withErrors($validasi);
        }

        if($request->hasFile('gambar_kategori'))
        {
            if($request->file('gambar_kategori')->isValid())
            {
                Storage::disk('upload')->delete($kategori->gambar_kategori);

                $gambar_kategori = $request->file('gambar_kategori');
                $extension = $gambar_kategori->getClientOriginalExtension();

                $namaFoto = "kategori/".date('YmdHis').".".$extension;
                $upload_path = 'public/uploads/kategori';
                $request->file('gambar_kategori')->move($upload_path, $namaFoto);
                $data['gambar_kategori'] = $namaFoto;
            }
        }

        $kategori->update($data);
        return redirect()->route('kategori.index')->with('status', 'Kategori berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $kategori = Kategori::findOrFail($id);
        $kategori->delete();
        Storage::disk('upload')->delete($kategori->gambar_kategori);
        return redirect()->route('kategori.index')->with('status', 'kategori berhasil dihapus');
    }
}

resources/views/kategori/create.blade.php
@extends('layouts.template')

@section('title')
    Tambah Data Kategori
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('kategori.store') }}" enctype="multipart/form-data">
          {{ csrf_field() }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="kategori" class="col-sm-2 control-label">Kategori</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="kategori" name="kategori" value="{{ old('kategori') }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="gambar_kategori" class="col-sm-2 control-label">Gambar Kategori</label>
                <div class="col-sm-10">
                  <input type="file" id="gambar_kategori" name="gambar_kategori" class="form-control"></input>
                </div>
              </div>                            

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('kategori.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Save</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/kategori/edit.blade.php
@extends('layouts.template')

@section('title')
    Update Data Kategori
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('kategori.update', [$kategori->kd_kategori]) }}" enctype="multipart/form-data">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="kategori" class="col-sm-2 control-label">Kategori</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="kategori" name="kategori" value="{{ $kategori->kategori }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="gambar_kategori" class="col-sm-2 control-label"></label>
                <div class="col-sm-10">
                  <img class="img-thumbnail" src="{{ asset('uploads/'.$kategori->gambar_kategori) }}" width="100px"  >
                </div>
              </div>

              <div class="form-group">
                <label for="gambar_kategori" class="col-sm-2 control-label">Gambar Kategori</label>
                <div class="col-sm-10">
                  <input type="file" id="gambar_kategori" name="gambar_kategori" class="form-control"></input>
                </div>
              </div>                            

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('kategori.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Update</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/kategori/index.blade.php
@extends('layouts.template')

@section('title')
    Data Kategori
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                @if(Request::get('keyword'))
                    <a class="btn btn-success" href="{{ route('kategori.index') }}">Back</a>
                @else
                    <a class="btn btn-success" href="{{ route('kategori.create') }}"><span class="glyphicon glyphicon-plus"></span> Create</a>
                @endif                

                <form method="get" action="{{route('kategori.index')}}">
                    <div class="form-group">
                    <label for="keyword" class="col-sm-2 control-label">Search By Name</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="keyword" name="keyword" value="{{ Request::get('keyword') }}">
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>
                    </div>
                    </div>
                </form>                            
            </div>
            <div class="panel panel-body">
                @if(Request::get('keyword'))
                    <div class="alert alert-success alert-block">
                        Hasil pencarian kategori dengan keyword : <b>{{ Request::get('keyword') }}</b>
                    </div>
                @endif

                @include('alert.success')

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Kategori</th>
                            <th>Gambar Kategori</th>                            
                            <th width="30%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($kategori as $row)
                            <tr>
                                <td>{{ $loop->iteration + ($kategori->perpage() * ($kategori->currentPage() -1) ) }}</td>
                                <td>{{ $row->kategori }}</td>
                                <td><img class="img-thumbnail" src="{{ asset('uploads/'.$row->gambar_kategori) }}" width="70px"/></td>                                
                                <td>                                    
                                    <form method="post" action="{{ route('kategori.destroy',[$row->kd_kategori]) }}" onsubmit="return confirm('Apakah Anda Yakin Akan Menghapus Data Ini?');">
                                    @csrf
                                    {{ method_field('delete') }}
                                        <a class="btn btn-warning" href="{{ route('kategori.edit', [$row->kd_kategori]) }}">Edit</a>
                                        <button type="submit" class="btn btn-danger">Delete</button>                                    
                                    </form>
                                </td>
                            </tr>                            
                        @endforeach
                    </tbody>
                </table>
                {{ $kategori->appends(Request::all())->links() }}                
            </div>
          </div>
        </div>
    </div>
@endsection

resources/views/kategori/show.blade.php
@extends('layouts.template')

@section('title')
    Detail Data User
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">                             
                <a class="btn btn-success" href="{{ route('user.index') }}">Back</a>                    
            </div>
            <div class="panel panel-body">            
                <table class="table table-bordered">
                    <tr>
                        <td>Username</td>
                        <td>:</td>
                        <td>{{ $user->username }}</td>
                    </tr>
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>:</td>
                        <td>{{ $user->email }}</td>
                    </tr>
                    <tr>
                        <td>Level</td>
                        <td>:</td>
                        <td>{{ $user->level }}</td>
                    </tr>
                </table>
            </div>
          </div>
        </div>
    </div>
@endsection