routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\AgenController;
use App\Http\Controllers\ReportPenjualanController;
use App\Http\Controllers\InfoCoronaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::match(["get","post"],"/register", function(){
    return redirect('login');
})->name("register");

Route::group(['middleware' => ['auth']], function(){
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user','App\Http\Controllers\UserController');
Route::resource('supplier', SupplierController::class)->except(['show']);
Route::resource('pegawai', PegawaiController::class)->except('show');
Route::resource('kategori', KategoriController::class)->except('show');
Route::resource('produk', ProdukController::class)->except('show');
Route::resource('transaksi_masuk', TransaksiMasukController::class)->only(['index', 'create', 'store', 'destroy']);
Route::get('agen', [AgenController::class, 'index'])->name('agen');
Route::get('report_penjualan', [ReportPenjualanController::class, 'index'])->name('report_penjualan');
Route::get('cetak_pdf', [ReportPenjualanController::class, 'cetak_pdf'])->name('cetak_pdf');
Route::get('cetak_excel', [ReportPenjualanController::class, 'cetak_excel'])->name('cetak_excel');
Route::get('corona', [InfoCoronaController::class, 'index'])->name('corona');


});

resources/views/subview/menu.blade.php
<nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="#" class="nav-link ">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Master
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>

            <ul class="nav nav-treeview">
              @if(Auth::user()->level == 'admin')
              <li class="nav-item">
                <a href="{{ route('user.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>User</p>
                </a>
              </li>
              @endif
              <li class="nav-item">
                <a href="{{ route('supplier.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Supplier</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('pegawai.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Pegawai</p>
                </a>
              </li>              
              <li class="nav-item">
                <a href="{{ route('kategori.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Kategori</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('produk.index') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Produk</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{{ route('agen') }}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Agen</p>
                </a>
              </li>
            </ul>
          </li>

          <li class="nav-item">
            <a href="{{ route('corona') }}" class="nav-link">
              <i class="nav-icon fas fa-radiation"></i>
              <p>
                Info Corona               
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{ route('transaksi_masuk.index') }}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Transaksi Masuk                
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="{{ route('report_penjualan') }}" class="nav-link">
              <i class="nav-icon fas fa-th"></i>
              <p>
                Report Penjualan                
              </p>
            </a>
          </li>
        </ul>
      </nav>