routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\KategoriController;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\TransaksiMasukController;
use App\Http\Controllers\AgenController;
use App\Http\Controllers\ReportPenjualanController;
use App\Http\Controllers\InfoCoronaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes();

Route::match(["get","post"],"/register", function(){
    return redirect('login');
})->name("register");

Route::group(['middleware' => ['auth']], function(){
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::resource('user','App\Http\Controllers\UserController');
Route::resource('supplier', SupplierController::class)->except(['show']);
Route::resource('pegawai', PegawaiController::class)->except('show');
Route::resource('kategori', KategoriController::class)->except('show');
Route::resource('produk', ProdukController::class)->except('show');
Route::resource('transaksi_masuk', TransaksiMasukController::class)->only(['index', 'create', 'store', 'destroy']);
Route::get('agen', [AgenController::class, 'index'])->name('agen');
Route::get('report_penjualan', [ReportPenjualanController::class, 'index'])->name('report_penjualan');
Route::get('cetak_pdf', [ReportPenjualanController::class, 'cetak_pdf'])->name('cetak_pdf');
Route::get('cetak_excel', [ReportPenjualanController::class, 'cetak_excel'])->name('cetak_excel');
Route::get('corona', [InfoCoronaController::class, 'index'])->name('corona');


});

app/Models/Pegawai.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Pegawai extends Model
{
    use HasFactory;

    public $incrementing = 'false';
    protected $table = 'pegawai';
    protected $primaryKey = 'username';
    protected $fillable = [
        'username',
        'password',
        'nama_pegawai',
        'jk',
        'alamat',
        'is_aktif'
    ];
    protected $keyType = 'string';
}

app/Http/Controllers/Api/PegawaiController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Pegawai;
use Validator;
use App\Http\Resources\PegawaiResource;

class PegawaiController extends Controller
{
    public function login_pegawai(Request $request)
    {
        $input = $request->all();
        $validasi = Validator::make($input, [
            'username'=> 'required',
            'password'=> 'required'
        ]);

        if($validasi->fails())
        {
            return response()->json([
                'status'=> FALSE,
                'msg'=> $validasi->errors()
            ], 400);
        }

        $username = $request->input('username');
        $password = $request->input('password');

        $pegawai = Pegawai::where([
            ['username', $username],
            ['is_aktif', 1]
        ])->first();

        if(is_null($pegawai))
        {
            //jika pegawai tidak ditemukan
            return response()->json([
                'status'=> FALSE,
                'msg'=> 'Username tidak ditemukan'
            ], 200);
        }
        else
        {
            //jika pegawai ditemukan
            if(password_verify($password, $pegawai->password))
            {
                //jika password sesuai
                return response()->json([
                    'status'=> TRUE,
                    'msg'=> 'Username ditemukan',
                    'pegawai'=> new PegawaiResource($pegawai)
                ], 200);
            }
            else
            {
                //jika password tidak sesuai
                return response()->json([
                    'status'=> FALSE,
                    'msg'=> 'Username & Password tidak sesuai'
                ], 200);
            }
        }
    }
}

app/Http/Controllers/PegawaiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Pegawai;
use Validator;
use Illuminate\Support\Arr;

class PegawaiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $pegawai = Pegawai::paginate(5);

        $filterKeyword = $request->get('keyword');
        if($filterKeyword)
        {
            $pegawai = Pegawai::where('nama_pegawai','LIKE',"%$filterKeyword%")->paginate(5);
        }
        return view('pegawai.index', compact('pegawai'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pegawai.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validasi = Validator::make($data, [
            'username'=> 'required|max:100|unique:pegawai',
            'password'=> 'required|min:6|max:50',
            'nama_pegawai'=> 'required|max:255',
            'alamat'=> 'required|max:255'            
        ]);

        if($validasi->fails())
        {
            return redirect()->route('pegawai.create')->withErrors($validasi)->withInput();
        }

        $data['password'] = password_hash($request->input('password'), PASSWORD_DEFAULT);
        Pegawai::create($data);
        return redirect()->route('pegawai.index')->with('status', 'Pegawai berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $pegawai = Pegawai::findOrFail($id);
        return view('pegawai.edit', compact('pegawai'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $pegawai = Pegawai::findOrFail($id);
        $data = $request->all();

        $validasi = Validator::make($data, [
            'password'=> 'sometimes|nullable|min:6|max:50',
            'nama_pegawai'=> 'required|max:255',
            'alamat'=> 'required|max:255'
        ]);

        if($validasi->fails())
        {
            return redirect()->route('pegawai.edit', [$id])->withErrors($validasi);
        }

        if($request->input('password'))
        {
            $data['password'] = password_hash($request->input('password'), PASSWORD_DEFAULT);
        }
        else
        {
            $data = Arr::except($data,['password']);
        }

        $pegawai->update($data);
        return redirect()->route('pegawai.index')->with('status', 'Pegawai berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $pegawai = Pegawai::findOrFail($id);
        $pegawai->delete();
        return redirect()->route('pegawai.index')->with('status', 'Pegawai berhasil didelete');
    }
}

resources/views/pegawai/create.blade.php
@extends('layouts.template')

@section('title')
    Tambah Data Pegawai
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('pegawai.store') }}">
          {{ csrf_field() }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="username" name="username" value="{{ old('username') }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="password" class="col-sm-2">Password</label>
                <div class="col-sm-10">
                  <input type="password" class="form-control" id="password" name="password" value=""></input>
                </div>
              </div>

              <div class="form-group">
                <label for="nama_pegawai" class="col-sm-2 control-label">Nama Pegawai</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="nama_pegawai" name="nama_pegawai" value="{{ old('nama_pegawai') }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="jk" class="col-sm-2 control-label">Jenis Kelamin</label>
                <div class="col-sm-10">
                  <select class="form-control" id="jk" name="jk">
                    <option value="PRIA">Pria</option>
                    <option value="WANITA">Wanita</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label for="alamat" class="col-sm-2 control-label">Alamat</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="alamat" name="alamat">{{ old('alamat') }}</textarea>
                </div>
              </div>

              <div class="form-group">
                <label for="is_aktif" class="col-sm-10 control-label">Status</label>
                <div class="col-sm-10">
                  <select name="is_aktif" id="is_aktif" class="form-control">
                    <option value="1">Aktif</option>
                    <option value="0">Tidak Aktif</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('pegawai.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Save</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pegawai/edit.blade.php
@extends('layouts.template')

@section('title')
    Edit Data Pegawai
@endsection

@section('content')
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default card">
        <div class="panel-heading">
          @include('alert.error')                           
        </div>

        <div class="panel-body">
          <form class="form-horizontal" method="post" action="{{ route('pegawai.update', [$pegawai->username]) }}">
          {{ csrf_field() }}
          {{ method_field('PUT') }}
            <div class="panel-body post-body">
              <div class="form-group ">
                <label for="username" class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="username" disabled value="{{ $pegawai->username }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="password" class="col-sm-2">Password</label>
                <div class="col-sm-10">
                  <input type="password" class="form-control" id="password" name="password" value=""></input>
                </div>
              </div>

              <div class="form-group">
                <label for="nama_pegawai" class="col-sm-2 control-label">Nama Pegawai</label>
                <div class="col-sm-10">
                  <input type="text" class="form-control" id="nama_pegawai" name="nama_pegawai" value="{{ $pegawai->nama_pegawai }}"></input>
                </div>
              </div>

              <div class="form-group">
                <label for="jk" class="col-sm-2 control-label">Jenis Kelamin</label>
                <div class="col-sm-10">
                  <select class="form-control" id="jk" name="jk">
                    <option value="PRIA" @if($pegawai->jk == "PRIA") selected @endif >Pria</option>
                    <option value="WANITA" @if($pegawai->jk == "WANITA") selected @endif>Wanita</option>
                  </select>
                </div>
              </div>

              <div class="form-group">
                <label for="alamat" class="col-sm-2 control-label">Alamat</label>
                <div class="col-sm-10">
                  <textarea class="form-control" id="alamat" name="alamat">{{ $pegawai->alamat }}</textarea>
                </div>
              </div>

              <div class="form-group">
                <label for="is_aktif" class="col-sm-10 control-label">Status</label>
                <div class="col-sm-10">
                  <select name="is_aktif" id="is_aktif" class="form-control">
                    <option value="1" @if($pegawai->is_aktif == 1) selected @endif >Aktif</option>
                    <option value="0" @if($pegawai->is_aktif == 0) selected @endif >Tidak Aktif</option>
                  </select>
                </div>
              </div>
            </div>

            <div class="panel-footer col-sm-10">    
              <a class="btn btn-info float-right" href="{{ route('pegawai.index') }}">Back</a>
              <button type="submit" name="tombol" class="btn btn-info float-right">Update</button>          
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/pegawai/index.blade.php
@extends('layouts.template')

@section('title')
    Data Pegawai
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                @if(Request::get('keyword'))
                    <a class="btn btn-success" href="{{ route('pegawai.index') }}">Back</a>
                @else
                    <a class="btn btn-success" href="{{ route('pegawai.create') }}"><span class="glyphicon glyphicon-plus"></span>Create</a>
                @endif                

                <form method="get" action="{{route('pegawai.index')}}">
                    <div class="form-group">
                    <label for="keyword" class="col-sm-2 control-label">Search By Name</label>
                    <div class="col-sm-4">
                        <input type="text" class="form-control" id="keyword" name="keyword" value="{{Request::get('keyword')}}">
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-info"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                    </div>
                    </div>
                </form>                            
            </div>
            <div class="panel panel-body">
                @if(Request::get('keyword'))
                    <div class="alert alert-success alert-block">
                        Hasil pencarian pegawai dengan keyword : <b>{{ Request::get('keyword') }}</b>
                    </div>
                @endif

                @include('alert.success')

                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th width="5%">No</th>
                            <th>Username</th>
                            <th>Nama Pegawai</th>
                            <th>Jenis Kelamin</th>
                            <th>Alamat</th>
                            <th>Is Aktif</th>
                            <th width="30%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($pegawai as $row)
                            <tr>
                                <td>{{ $loop->iteration + ($pegawai->perPage() * ($pegawai->currentPage() -1) ) }}</td>
                                <td>{{ $row->username }}</td>
                                <td>{{ $row->nama_pegawai }}</td>
                                <td>{{ $row->jk }}</td>
                                <td>{{ $row->alamat }}</td>
                                <td>@if($row->is_aktif == 1) Aktif @else Tidak Aktif @endif</td>
                                <td>
                                    
                                    <form method="post" action="{{ route('pegawai.destroy',[$row->username]) }}" onsubmit="return confirm('Apakah Anda Yakin Akan Menghapus Data Ini?');">
                                    @csrf
                                    {{ method_field('delete') }}
                                        <a class="btn btn-warning" href="{{ route('pegawai.edit', [$row->username]) }}">Edit</a>
                                        <button type="submit" class="btn btn-danger">Delete</button>                                        
                                    </form>
                                </td>
                            </tr>                            
                        @endforeach
                    </tbody>
                </table>
                {{ $pegawai->appends(Request::all())->links() }}                
            </div>
          </div>
        </div>
    </div>
@endsection

resources/views/pegawai/show.blade.php
@extends('layouts.template')

@section('title')
    Detail Data User
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">                             
                <a class="btn btn-success" href="{{ route('user.index') }}">Back</a>                    
            </div>
            <div class="panel panel-body">            
                <table class="table table-bordered">
                    <tr>
                        <td>Username</td>
                        <td>:</td>
                        <td>{{ $user->username }}</td>
                    </tr>
                    <tr>
                        <td>Nama</td>
                        <td>:</td>
                        <td>{{ $user->name }}</td>
                    </tr>
                    <tr>
                        <td>Email</td>
                        <td>:</td>
                        <td>{{ $user->email }}</td>
                    </tr>
                    <tr>
                        <td>Level</td>
                        <td>:</td>
                        <td>{{ $user->level }}</td>
                    </tr>
                </table>
            </div>
          </div>
        </div>
    </div>
@endsection